flask_server/OPTIMEyes/routes_blueprint.py
# import functools - https://flask.palletsprojects.com/en/2.0.x/tutorial/views/
import requests
import couchdb
import io
import json
import base64
import pdb
import zipfile

from flask import (
    make_response,
    current_app,
    Blueprint,
    flash,
    redirect,
    render_template,
    request,
    jsonify,
    send_file,
)

from flask_login import login_required, current_user

# self written utils
from .utils.makeTask import makeTask
from .utils.makeClassifyList import makeClassifyList
from .utils.makeCompareList import makeCompareList
from .utils.makeFlickerList import makeFlickerList
from .utils.makeSliderList import makeSliderList
from .utils.makeMonaiSegmentationList import makeMonaiSegmentationList
from .utils.makeMonaiSegmentationOCTList import makeMonaiSegmentationOCTList
from .utils.addImages import addImages
from .utils.deleteImageSet import deleteImageSet

# DB
from OPTIMEyes.db import get_server

bp = Blueprint('routes_blueprint', __name__, url_prefix='/')

# please delete this when you can...it's so bad
def check_if_admin_party_then_make_request(url, method="GET", data="no data"):
    """
    Checks if we are in admin part and if so sends necessary credentials
    """
    if method == "GET":
        if current_app.config['ADMIN_PARTY']:
            response = requests.get('{}'.format(url))
        else:
            response = requests.get('{}'.format(
                url), auth=(current_app.config["COUCHDB_USER"], current_app.config["COUCHDB_PASSWORD"]))
    elif method == "PUT":
        if current_app.config['ADMIN_PARTY']:
            response = requests.put(url, data=data)
        else:
            response = requests.put(
                url, data=data, auth=(current_app.config["COUCHDB_USER"], current_app.config["COUCHDB_PASSWORD"]))
    elif method == "DELETE":
        if current_app.config['ADMIN_PARTY']:
            response = requests.delete(url)
        else:
            response = requests.delete(
                url, auth=(current_app.config["COUCHDB_USER"], current_app.config["COUCHDB_PASSWORD"]))
    return response


@bp.route('/configuration', methods=['GET'])
def config():
    
    """
    For the front end
    """
    try:
        USER_INFO = {"username":current_user.username, 
                     "logged_in":current_user.is_authenticated,
                     "admin":current_user.admin}
    except:
        USER_INFO = {"logged_in":current_user.is_authenticated}
    config = {
        "DNS": current_app.config['DNS'],
        "COUCH_DB": current_app.config['COUCH_DB'],
        "DB_PORT": current_app.config['DB_PORT'],
        "HTTP_PORT": current_app.config['HTTP_PORT'],
        "ADMIN_PARTY": current_app.config['ADMIN_PARTY'],
        "SSL": current_app.config['SSL'],
        "USER_INFO": USER_INFO
    }
    return jsonify(config)


# Navigation
@bp.route('/', methods=['GET'])
def vue_index():
    return render_template('/vuetify_components/index.html')

@bp.route('/main_dashboard', methods=['GET'])
@login_required
def main_dashboard():
    return render_template('/vuetify_components/main_dashboard.html')

@bp.route('/imagesDashboard', methods=['GET'])
@login_required
def imagesDashboard():
    # pdb.set_trace()
    return render_template('/vuetify_components/imagesDashboard.html')

@bp.route('/image_set_summary/<imageSet>', methods=['GET'])
@login_required
def image_set_summary(imageSet):
    return render_template('/vuetify_components/ImageSetSummary.html', imageSet=imageSet)

@bp.route('/tasksList', methods=['GET'])
@login_required
def tasksList():
    return render_template('/vuetify_components/tasksList.html')

## Apps
@bp.route('/classifyApp/<user>/<list_name>', methods=['GET'])
@login_required
def classifyApp(user, list_name):
    task_dict = {"user":user, "list_name":list_name}
    return render_template('/vuetify_components/classifyApp.html', task=task_dict)

@bp.route('/compareApp/<user>/<list_name>', methods=['GET'])
@login_required
def compareApp(user, list_name):
    task_dict = {"user":user, "list_name":list_name}
    return render_template('/vuetify_components/compareApp.html', task=task_dict)

@bp.route('/flickerApp/<user>/<list_name>', methods=['GET'])
@login_required
def flickerApp(user, list_name):
    task_dict = {"user":user, "list_name":list_name}
    return render_template('/vuetify_components/flickerApp.html', task=task_dict)

@bp.route('/sliderApp/<user>/<list_name>', methods=['GET'])
@login_required
def sliderApp(user, list_name):
    task_dict = {"user":user, "list_name":list_name}
    return render_template('/vuetify_components/sliderApp.html', task=task_dict)

@bp.route('/monaiSegmentationApp/<user>/<list_name>', methods=['GET'])
@login_required
def monaiSegmentationApp(user, list_name):
    task_dict = {"user":user, "list_name":list_name}
    return render_template('/vuetify_components/monaiSegmentationApp.html', task=task_dict)

@bp.route('/monaiSegmentationOCTApp/<user>/<list_name>', methods=['GET'])
@login_required
def monaiSegmentationOCTApp(user, list_name):
    task_dict = {"user":user, "list_name":list_name}
    return render_template('/vuetify_components/monaiSegmentationOCTApp.html', task=task_dict)




@bp.route('/ohif', methods=['GET'])
@login_required
def ohif():
    return render_template('/vuetify_components/ohif.html')



# APIs
@bp.route('/add_images', methods=['POST'])
def add_images():
    print("in /add_images")
    folder=request.form['folder']
    imageSetName=request.form['imageSetName']
    imageSetTypeSelect=request.form['imageSetTypeSelect']
    addImages(folder, imageSetName, imageSetTypeSelect)
    return redirect('/imagesDashboard')
   
@bp.route('/delete_image_set/<imageSet>', methods=['DELETE'])
def delete_image_set(imageSet):
    print("in /delete_image_set")
    deleted_images = deleteImageSet(imageSet)
    return deleted_images
       
@bp.route('/make_task', methods=['POST'])
def make_task():
    #pdb.set_trace()
    print("in /make_task")
    new_task = json.loads(request.data)
    user=new_task['user']
    imageSetName=new_task['imageSetName'] # pre-existing; imageSet
    imageListTypeSelect=new_task['imageListTypeSelect']
    pctRepeat = 0
    taskOrder=new_task['taskOrder']
    # pdb.set_trace()
    if imageListTypeSelect == "classify":
        listName=f"{imageSetName}-{imageListTypeSelect}-{pctRepeat}" # Placeholder and won't allow duplicates; add form entry to truly customze and add duplicates
        makeClassifyList(imageSet=imageSetName, classifyListName=listName, pctRepeat=pctRepeat)
    elif imageListTypeSelect == "compare":
        listName=f"{imageSetName}-{imageListTypeSelect}-{pctRepeat}" # Placeholder and won't allow duplicates; add form entry to truly customze and add duplicates
        makeCompareList(imageSet=imageSetName, compareListName=listName, pctRepeat=pctRepeat)
    elif imageListTypeSelect == "flicker":
        listName=f"{imageSetName}-{imageListTypeSelect}-{pctRepeat}" # Placeholder and won't allow duplicates; add form entry to truly customze and add duplicates
        makeFlickerList(imageSet=imageSetName, flickerListName=listName, pctRepeat=pctRepeat)
    elif imageListTypeSelect == "slider":
        listName=f"{imageSetName}-{imageListTypeSelect}-{pctRepeat}" # Placeholder and won't allow duplicates; add form entry to truly customze and add duplicates
        makeSliderList(imageSet=imageSetName, sliderListName=listName, pctRepeat=pctRepeat)
    elif imageListTypeSelect == "monaiSegmentation":
        listName=f"{imageSetName}-{imageListTypeSelect}-{pctRepeat}" # Placeholder and won't allow duplicates; add form entry to truly customze and add duplicates
        makeMonaiSegmentationList(imageSet=imageSetName, monaiSegmentationListName=listName, pctRepeat=pctRepeat)
    elif imageListTypeSelect == "monaiSegmentationOCT":
        listName=f"{imageSetName}-{imageListTypeSelect}-{pctRepeat}" # Placeholder and won't allow duplicates; add form entry to truly customze and add duplicates
        makeMonaiSegmentationOCTList(imageSet=imageSetName, monaiSegmentationOCTListName=listName, pctRepeat=pctRepeat)
    elif imageListTypeSelect == "grid":
        pass
    elif imageListTypeSelect == "pair":
        pass
    makeTaskMessage = makeTask(user=user, imageListName=listName, imageSet=imageSetName, imageListType=imageListTypeSelect, taskOrder=taskOrder)
    return json.dumps(makeTaskMessage)
    
@bp.route('/get_image_sets', methods=['GET'])
def get_image_sets():
    print("in /get_image_sets")
    base = "http://{}:{}/{}".format(
        "couchdb", current_app.config["DB_PORT"], current_app.config["COUCH_DB"])
        # current_app.config['DNS'], current_app.config["DB_PORT"], current_app.config["COUCH_DB"])
    view = f"_design/images/_view/images?group_level=1"
    url = f"{base}/{view}"
    response = check_if_admin_party_then_make_request(url)
    return json.loads(response.content.decode('utf-8'))

@bp.route('/get_images_by_set/<imageSet>', methods=['GET'])
def get_images_by_set(imageSet):
    """_summary_

    Args:
        imageSet (_type_): image set or raw images set name

    Returns:
        _type_: set of image ids from the database
    """
    print("in /get_images_by_set")
    base = "http://{}:{}/{}".format(
        "couchdb", current_app.config["DB_PORT"], current_app.config["COUCH_DB"])
        # current_app.config['DNS'], current_app.config["DB_PORT"], current_app.config["COUCH_DB"])
    view = f'_design/images/_view/imagesBySet?key="{imageSet}"'
    url = f"{base}/{view}"
    response = check_if_admin_party_then_make_request(url)
    return json.loads(response.content.decode('utf-8'))

@bp.route('/get_tasks/<app>', methods=['GET'])
def get_tasks(app):
    username = request.args['username']
    base = "http://{}:{}/{}".format(
        "couchdb", current_app.config['DB_PORT'], current_app.config["COUCH_DB"])
        # current_app.config['DNS'], current_app.config['DB_PORT'], current_app.config["COUCH_DB"])

flask_server/OPTIMEyes/templates/vuetify_components/ImageSetSummary.html
<!-- TEMPLATE -->
{% extends "vuetify_components/base.html" %}

<!-- TITLE -->
{% block title %}Image Set Summary{% endblock %}

<!-- CSS -->
{% block custom_css %}
{% endblock %}



<!-- BODY -->
{% block content %}

<!-- Components -->
{% include 'vuetify_components/navbar.html' %}

<!-- Index Vue App -->
<div id="imageSetSummary">
    <v-app>
        <navbar-tag></navbar-tag>
      <v-main>
          <v-container>
            <div>
              <h1>[[ message ]]</h1>
  
              <v-select
                v-model="cols_selected"
                :items="columns"
                label="Columns"
                outlined
              ></v-select>
            </div>

            <v-row>
              <v-col
                v-for="image in images"
                :key="image.value._id"
                class="d-flex child-flex"
                :cols="grid_cols"
              >
                <v-card>
                
                  <v-img
                    :src="image.value.base64"
                    :lazy-src="image.value.base64"
                    aspect-ratio="1"
                    class="grey lighten-2"
                  >
                    <template v-slot:placeholder>
                      <v-row
                        class="fill-height ma-0"
                        align="center"
                        justify="center"
                      >
                        <v-progress-circular
                          indeterminate
                          color="grey lighten-5"
                        ></v-progress-circular>
                      </v-row>
                    </template>
                  </v-img>

                  <v-card-text>
                    [[ image.value._id ]]
                  </v-card-text>

                </v-card>

              </v-col>
            </v-row>

          </v-container>
      </v-main>
    </v-app>
</div>

{% endblock %}



{% block js_scripts %}

<script>

var imageSetSummary =new Vue({
    el: '#imageSetSummary',
    vuetify: new Vuetify(),

    data: () => ({
        message: `Image Set: {{ imageSet }} `,
        imageSet: "{{ imageSet }}",
        images: [],
        // select
        columns: [1,2,3,4,6,12],
        cols_selected: 12,

    }),
    async mounted() {
      configuration = await this.getConfiguration()
      this.DNS = configuration.DNS;
      this.SSL = configuration.SSL;
      this.COUCH_DB = configuration.COUCH_DB;
      this.DB_PORT = configuration.DB_PORT;
      this.HTTP_PORT = configuration.HTTP_PORT;
      this.ADMIN_PARTY = configuration.ADMIN_PARTY;
      this.USER_INFO = configuration.USER_INFO;
      this.buildGrid();    
    },

    computed: {
      // General
      URLS() {
          return {
              // old ${this.SSL===true ? 'https' : 'http'}://${this.DNS}:${this.HTTP_PORT}
              configuration: "/configuration",
              getImagesBySet: `/get_images_by_set`
          }
      },
      grid_cols() {
        grid_col_key = {1:12, 2:6, 3:4, 4:3, 6:2, 12:1 }
        return grid_col_key[this.cols_selected]
      }

    },
    methods: {
      async getConfiguration() {
          // https://dmitripavlutin.com/javascript-fetch-async-await/
          const response = await fetch('/configuration');
          if (!response.ok) {
              const message = `An error has occured: ${response.status}`;
              throw new Error(message);
          }
          const configuration = await response.json();
          return configuration;
      },
      buildGrid() {
        console.log("buildGrid")
        getImagesBySetURL = this.URLS.getImagesBySet + `/${this.imageSet}`
        fetch(getImagesBySetURL)
            .then((response) => response.json())
            .then((data) => {
              data.rows.forEach((v, i, a) => {
                v['value']['base64'] = ''
                this.images.push(v)
                this.getBase64DataOfImageFromCouch(v['id'])

              })
              
            })
      },
      getBase64DataOfImageFromCouch(image_id) {
        // old ${this.SSL===true ? 'https' : 'http'}://${this.DNS}:${this.HTTP_PORT}
        var url = `/get_image/${image_id}`
        let ILS = this; // Image Set Summary Vue Object
        let I_ID = image_id;
        fetch(url)
          .then(response => {
            return response.text();
          })
          .then(data => {
            DATA='data:image/png;base64,' + data
            ILS.images.forEach((v,i,a)=>{
              if (v['value']['_id'] === I_ID){
                ILS.images[i]['value']['base64'] = DATA
              }
            })
          })
      },
    },

    delimiters: ['[[',']]'],
})
</script>


{% endblock %}

flask_server/OPTIMEyes/templates/vuetify_components/imagesDashboard.html
<!-- TEMPLATE -->
{% extends "vuetify_components/base.html" %}

<!-- TITLE -->
{% block title %}Images Dashboard{% endblock %}

<!-- CSS -->
{% block custom_css %}
{% endblock %}



<!-- BODY -->
{% block content %}

<!-- Components -->
{% include 'vuetify_components/navbar.html' %}

<!-- Index Vue App -->
<div id="imagesDashboard">
    <v-app>
        <navbar-tag></navbar-tag>
      <v-main>
          <v-container>
            <v-row>
              <v-col cols=6>
                <h2>Image Sets:</h2>
                
                <v-alert
                  color="red"
                  elevation="4"
                  type="success"
                  v-if="message != null"
                >
                  <p>[[ message ]]</p>
                </v-alert>
                <v-alert
                  color="red"
                  elevation="4"
                  type="success"
                  v-if="deleted_images != null"
                >
                  <p>Deleted [[ deleted_images.count ]] images.</p>
                  <ul v-for="image in deleted_images.image_ids">
                    <li>[[ image ]]</li>
                  </ul>
                </v-alert>

                <v-simple-table
                v-if="admin"
                >
                  <template v-slot:default>
                    <thead>
                      <tr>
                        <th class="text-left">
                          Image Set
                        </th>
                        <th class="text-left">
                          Images
                        </th>
                        <th class="text-left">
                          Action
                        </th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr
                        v-for="item in imageSets"
                        :key="item.imageSet"
                      >
                        <td>
                          <v-btn
                          elevation="2"
                          @click="goToImageSummary([[ item.imageSet ]])" 
                          >[[ item.imageSet ]]</v-btn>
                        </td>
                        <td>[[ item.images ]]</td>
                        <td>
                          <v-btn
                          v-if="admin"
                          elevation="2"
                          @click="deleteImageSet([[ item.imageSet ]])" 
                          >Delete</v-btn>
                        </td>
                      </tr>
                    </tbody>
                  </template>
                </v-simple-table>

              </v-col>

              <v-col v-if="admin" cols=6>
                <v-alert
                  v-if="admin"
                  color="blue"
                  elevation="4"
                  type="success"
                >Make sure you've moved the data you want to upload to the Image-Comparator-Data directory within a folder. Enter the folder name into the form so the app knows where to get the data.
                </v-alert>
                <h2>Create Image Set:</h2>
                <v-form action="/add_images" method="post" ref="form">
                  <v-text-field
                    name="folder"
                    v-model="folder"
                    :error-messages="folderErrors"
                    :counter="70"
                    label='Folder within "Image-Comparator-Data" Folder'
                    required
                    @input="$v.folder.$touch()"
                    @blur="$v.folder.$touch()"
                  ></v-text-field>
                  <v-text-field
                    name="imageSetName"
                    v-model="imageSetName"
                    :error-messages="imageSetNameErrors"
                    label="Image Set Name"
                    required
                    @input="$v.imageSetName.$touch()"
                    @blur="$v.imageSetName.$touch()"
                  ></v-text-field>
                  <v-select
                  name="imageSetTypeSelect"
                  v-model="imageSetTypeSelect"
                  :items="imageSetTypeSelectItems"
                  :error-messages="imageSetTypeSelectErrors"
                  label="Image Set Type"
                  required
                  @change="$v.imageSetTypeSelect.$touch()"
                  @blur="$v.imageSetTypeSelect.$touch()"
                ></v-select>

                  <v-btn
                    class="mr-4"
                    @click="submit"
                  >
                    submit
                  </v-btn>
                  <v-btn @click="clear">
                    clear
                  </v-btn>
                </v-form>
              </v-col>


            </v-row>

          </v-container>
      </v-main>
    </v-app>
</div>

{% endblock %}



{% block js_scripts %}
<script src="https://cdn.jsdelivr.net/npm/vuelidate/dist/vuelidate.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vuelidate/dist/validators.min.js"></script>


<script>
const { required, maxLength } = validators
const validationMixin = vuelidate.validationMixin

Vue.use(vuelidate.default)

var template_app =new Vue({
    el: '#imagesDashboard',
    vuetify: new Vuetify(),
    mixins: [validationMixin],

    validations: {
      folder: { required, maxLength: maxLength(70) },
      imageSetName: { required },
      imageSetTypeSelect: { required },
    },

    data: () => ({
        message: null,
        imageSets: [],
        // form data
        admin: false,
        folder: '',
        imageSetName: '',
        imageSetTypeSelect: null,
        imageSetTypeSelectItems: ['non-DICOM', 'DICOM'],
        // delete variables
        deleted_images: null

    }),
    
    async mounted() {
      configuration = await this.getConfiguration()
      this.DNS = configuration.DNS;
      this.SSL = configuration.SSL
      
      this.COUCH_DB = configuration.COUCH_DB;
      this.DB_PORT = configuration.DB_PORT;
      this.HTTP_PORT = configuration.HTTP_PORT;
      this.ADMIN_PARTY = configuration.ADMIN_PARTY;
      this.USER_INFO = configuration.USER_INFO;
      this.admin = this.USER_INFO.admin
      if(!this.admin){
        this.message = "Non admins can't see image sets";
          setTimeout(()=>{this.message = null;}, 2000);
      }
      this.getImageSets();
  },

  computed: {
    // General
    URLS() {
        return {
            // old ${this.SSL===true ? 'https' : 'http'}://${this.DNS}:${this.HTTP_PORT}
            configuration: "/configuration",
            getImageSets: `/get_image_sets`,
            goToImageSummary: `/image_set_summary`,
            deleteImageSet: `/delete_image_set`,
        }
    },
    // Right Column
    folderErrors() {
        const errors = []
        if (!this.$v.folder.$dirty) return errors
        !this.$v.folder.maxLength && errors.push('Folder must be at most 70 characters long')
        !this.$v.folder.required && errors.push('Folder is required.')
        return errors
    },
    imageSetNameErrors() {
        const errors = []
        if (!this.$v.imageSetName.$dirty) return errors
        !this.$v.imageSetName.required && errors.push('User is required.')
        return errors
    },
    imageSetTypeSelectErrors() {
        const errors = []
        if (!this.$v.imageSetTypeSelect.$dirty) return errors
        !this.$v.imageSetTypeSelect.required && errors.push('Set Type is required.')
        return errors
    },
  },

  methods: {
    async getConfiguration() {
      // https://dmitripavlutin.com/javascript-fetch-async-await/
      const response = await fetch('/configuration');
      if (!response.ok) {
          const message = `An error has occured: ${response.status}`;
          throw new Error(message);
      }
      const configuration = await response.json();
      return configuration;
    },
    getImageSets() {
      console.log("getImageSets")
      
      fetch(this.URLS.getImageSets)
          .then((response) => response.json())
          .then((data) => {
              
              data.rows.forEach((v, i, a) => {
                cleaned_data = {imageSet:v.key[0], images: v.value}
                this.imageSets.push(cleaned_data)
              })
          })
    },
    deleteImageSet(imageSet) {
      console.log("deleteImageSet")
      IL = imageSet[0][0];
      fetch(this.URLS.deleteImageSet+`/${imageSet}`, {
        method: 'DELETE',
      })
      .then((response) => response.json())
      .then((data) => {
        this.deleted_images = data
        setTimeout(()=>{
          this.deleted_images = null;
          this.imageSets.forEach((v,i,a)=>{
            if (v['imageSet'] === IL){
              this.imageSets.splice(i, 1)
            }
          })
        }, 2000)
      })
    },
    goToImageSummary(imageSet) {
      console.log("goToImageSummary")
      window.location.replace(this.URLS.goToImageSummary + `/${imageSet}`)
    },
    // Right Column
    submit() {
      this.$v.$touch()
      this.$refs.form.$el.submit()
    },
    clear() {
      this.$v.$reset()
      this.folder = ''
      this.imageSetName = ''
      this.imageSetTypeSelect = ''
    },


  },

    delimiters: ['[[',']]'],
  })
</script>


{% endblock %}

flask_server/OPTIMEyes/templates/vuetify_components/navbar.html
<script type="text/template" id="navbar">
    <div>
        <v-app-bar
        color="black accent-4"
        dense
        dark
        app
        collapse-on-scroll
        >
        <v-app-bar-nav-icon @click="drawer = true"> </v-app-bar-nav-icon>

          <v-toolbar-title
            color="blue"
            v-if=config.USER_INFO.logged_in
            >
            Welcome [[ config.USER_INFO.username ]]
          </v-toolbar-title>
            <!-- <v-toolbar-title
            color="blue"
            v-if=config.USER_INFO.logged_in
            >
            (DEV ENVIRONMENT) Welcome [[ config.USER_INFO.username ]]
          </v-toolbar-title> -->
        
            <v-spacer></v-spacer>
            <v-btn elevation="2" 
            v-if="!config.USER_INFO.logged_in"
            href="/signup"
            >Sign Up</v-btn>

            <div v-if=!config.USER_INFO.logged_in>|</div>

            <v-btn elevation="2" 
            v-if=!config.USER_INFO.logged_in
            href="/login"
            >Login</v-btn>

            <!-- <v-toolbar-title v-if="logged_in">Logout</v-toolbar-title> -->

            <v-menu
            right
            bottom
            v-if=config.USER_INFO.logged_in
            >
                <template v-slot:activator="{ on, attrs }">
                    <v-btn
                    icon
                    v-bind="attrs"
                    v-on="on"
                    >
                    <v-icon>mdi-account</v-icon>
                    </v-btn>
                </template>
        
                <v-list>
                    <v-list-item
                    v-for="(menu_item, i) in menu_items"
                    :key="i"
                    @click="() => {}"
                    >
                    <v-list-item-title>
                        <v-btn
                        block
                        v-on:click="test(menu_item)"
                        >[[ menu_item ]]</v-btn>
                    </v-list-item-title>
                    </v-list-item>
                </v-list>
            </v-menu>
        </v-app-bar>

       <!-- Links to <v-app-bar-nav-icon></v-app-bar-nav-icon> -->
        <v-navigation-drawer v-model="drawer" absolute temporary>
            <v-list nav dense>
              <v-list-item-group
                v-model="group"
                active-class="deep-purple--text text--accent-4"
              >
                <v-list-item>
                  <v-list-item-icon>
                    <v-icon>mdi-home</v-icon>
                  </v-list-item-icon>
                  <v-list-item-title>
                    <a href="{{url_for('routes_blueprint.vue_index')}}">Home</a>
                  </v-list-item-title>
                </v-list-item>

                <v-list-item>
                  <v-list-item-icon>
                    <v-icon>mdi-view-dashboard</v-icon>
                  </v-list-item-icon>
                  <v-list-item-title>
                    <a href="{{url_for('routes_blueprint.main_dashboard')}}">Main Personal Dashboard</a>
                  </v-list-item-title>
                </v-list-item>

                <v-list-item v-if="config.USER_INFO.admin">
                  <v-list-item-icon>
                    <v-icon>mdi-image-multiple-outline</v-icon>
                  </v-list-item-icon>
                  <v-list-item-title>
                    <a href="{{url_for('routes_blueprint.imagesDashboard')}}">Images Dashboard</a>
                  </v-list-item-title>
                </v-list-item>

                <v-list-item>
                  <v-list-item-icon>
                    <v-icon>mdi-file-tree</v-icon>
                  </v-list-item-icon>
                  <v-list-item-title>
                    <a href="{{url_for('routes_blueprint.tasksList')}}">Tasks</a>
                  </v-list-item-title>
                </v-list-item>

                <!--
                <v-list-item>
                  <v-list-item-icon>
                    <v-icon>mdi-application-braces</v-icon>
                  </v-list-item-icon>
                  <v-list-item-title>
                    <a href="{{url_for('routes_blueprint.ohif')}}">OHIF</a>
                  </v-list-item-title>
                </v-list-item>-->

              </v-list-item-group>
            </v-list>
        </v-navigation-drawer>

    </div>

</script>

<script>
    Vue.component('navbar-tag', {
        template: '#navbar',
        data: function() {
            return { 
                URLS: {
                    "Sign Up": "/signup",
                    "Login": "/login",
                    "Logout": "/logout",
                },
                drawer:false,
                group:null,
                menu_items: ['Logout'], // ['Sign Up', 'Login', 'Logout']
                config: {USER_INFO: {"logged_in":false} },
            }
        },
        delimiters: ['[[',']]'],
        beforeCreate() {},
        created() {},
        beforeMount() {
            
        },
        mounted() {
            this.get_config()
        },
        methods: {
            get_config: function (){
                fetch('/configuration')
                .then((response) => response.json())
                .then((data) => {
                  this.config = data
                });
            },
            test: function (nav_button){
                console.log(nav_button)
                console.log(this.URLS[nav_button])
                window.location.href = this.URLS[nav_button];
                // window.open(this.URLS[nav_button])
            }
        },
    });
</script>

flask_server/OPTIMEyes/templates/vuetify_components/template-component.html
<script type="text/template" id="template-component">
    <div>
        [[ title ]]
    </div>
</script>

<script>
// this is the JS file, eg app.js
Vue.component('template-component', {
    template: '#template-component',
    data() {
        return { title: 'template-component' }
    },
    delimiters: ['[[',']]'],
});
</script>